### ISSUE TITLE
Improve JSON-LD configuration via templating

### ISSUE THREAD

**Issue by ksonda** [cgs-earth/pygeoapi#1]
**Is your feature request related to a problem? Please describe.**
@dblodgett-usgs and I have been working through how to use pygeoapi to render some fairly complicated JSON-LD ([example](https://github.com/internetofwater/docs.geoconnex.us/wiki/hydrologic-location-json-ld-guidance)). It is impossible to successfully create JSON-LD with nested properties/predicates from a rectangular data structure using the existing pygeoapi context configuration framework. 

**Describe the solution you'd like**
As an alternative to the context specification, I would simply like to be able to supply either a weblink or a local path to a JSON-LD template, something like [this](https://github.com/internetofwater/docs.geoconnex.us/wiki/hydrologic-location-template). With a full context and property structure, and "environmental variables" corresponding to fields from the pygeoapi data provider or rendered geojson properties for a given item. The geometry parts  maybe don't need to be part of the template, but could inherit the current json-ld generator functions that auto-generate geosparql and schema:geo geometry depending on the geometry type. 

**Describe alternatives you've considered**
The alternative would be to make context specification much more complex, allowing for nested properties. but the wisdom of allowing arbitrary complexity in the config yaml file vs just a dedicated template is lost on me.

**Additional context**
@alpha-beta-soup @tomkralidis @pvgenuchten @webb-ben may be interested.
Not sure if this has consequences for api.py refactor.

**Comment by tomkralidis** [comment]
One option is extending the existing pygeoapi config `context` object to support a `template` property, which would be a Jinja2 template on disk.  When a user requests, say, an `.../items/{itemId}` endpoint with `f=jsonld`, this would then trigger the JSON-LD to be generated from the template (if specified) vs. existing workflow.  Thoughts?

**Comment by ksonda** [comment]
Oh welcome to the fork! This seems reasonable. My only hesitation is that this requires someone to back out a jinja template from the json-ld template they want. If this is more parsimonious to implement for pygeoapi than text replacement of a json-ld document with variables I'm open, but would want to eventually invest in tooling to generate jinja templates from json-ld.

**Comment by ksonda** [comment]
Note that shapely stuff may need to be changed. See some of these logs I'm getting lately on json-ld retrievals:

```
/pygeoapi/pygeoapi/linked_data.py:259: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiPolygon()' or 'MultiPolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiPolygon()' constructor instead.

  geom = asShape(geo)

Exception ignored in: <function BaseGeometry.__del__ at 0x400553dd30>

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/shapely/geometry/base.py", line 209, in __del__

    self._empty(val=None)

  File "/usr/lib/python3/dist-packages/shapely/geometry/base.py", line 199, in _empty

    self._is_empty = True

  File "/usr/lib/python3/dist-packages/shapely/geometry/proxy.py", line 44, in __setattr__

    object.__setattr__(self, name, value)
```

**Comment by webb-ben** [comment]
Hi both. Jinja is definitely the way to go! With the (very small) changes made in this [branch of pygeoapi](https://github.com/geopython/pygeoapi/compare/master...cgs-earth:jsonld?expand=1), I have been able to render json-ld templates. [This is](https://github.com/internetofwater/geoconnex.us/tree/jsonld/pygeoapi) my kind of lazy docker test setup if you would like to test yourselves. I committed my templates directly to pygeoapi repository above, but as long as the templates are accessible in the jinja templates folder (default or set in pygeoapi config) the templating should work. 
[Current](https://reference.geoconnex.us/collections/gages/items/1185576?f=json) -> [Template](https://github.com/cgs-earth/pygeoapi/blob/jsonld/pygeoapi/templates/jsonld/hydrologic-location.json-ld) -> [Output](https://bpa.st/DU7A)

**Comment by ksonda** [comment]
Implemented in internetofwater fork https://github.com/internetofwater/pygeoapi/commit/cba2d0ad83e6f8bedd4051a8e1ddc1cd8d689829
